# NOT SUPPOSED TO RUN IN SWARM MODE

version: "3.9"

services:
  # Frp to tunnel connections to clients
  frp:
    image: ghcr.io/nekoluka/frp-docker:main
    restart: unless-stopped
    volumes:
      - ./frp.ini:/frp.ini
    environment:
      - RUN_FRPS=true
      - FRP_CONFIG_FILE=/frp.ini
      - FRP_VERSION=0.51.3
    ports:
      - "7000:7000"

  # Headscale to manage all tailscale clients
  headscale:
    image: headscale/headscale
    restart: unless-stopped
    volumes:
      - headscale_config:/etc/headscale/
      - ./headscale.conf.yml:/etc/headscale/config.yaml
    command: headscale serve

  # Caddy to handle all the http traffic
  caddy:
    image: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  caddy_data:
  caddy_config:
  headscale_config:
