version: '3.3'

services:
  slapd:
    user: root
    image: bitnami/openldap
    restart: unless-stopped
    environment:
      LDAP_ADMIN_PASSWORD: Operator2022!
      LDAP_ROOT: dc=homelab,dc=local
      LDAP_CONFIG_ADMIN_ENABLED: 1
      LDAP_CONFIG_ADMIN_USERNAME: configadmin
    ports:
      - 389:1389
    volumes:
      - ./loginUser.ldif:/custom/loginUser.ldif
      - ./openldap-container:/bitnami/openldap/:rw
    deploy:
      resources:
        limits:
          memory: 10M
  radius:
    build: 
      context: ../freeradius-with-ldap-auth
    restart: unless-stopped
    ports: 
      - 1812:1812/udp
    volumes:
      - ../freeradius-with-ldap-auth/ldap.conf:/etc/raddb/mods-available/ldap
    deploy:
      resources:
        limits:
          memory: 15M
  pihole:
    image: pihole/pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      TZ: Europe/Amsterdam
      WEBPASSWORD: Operator2022!
    volumes:
      - ./etc-pihole:/etc-pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    deploy:
      resources:
        limits:
          memory: 30M
