alerting:
  ntfy:
    url: # Your url
    topic: "test"
    priority: 4
    token: secret_token
    default-alert:
      enabled: true
      failure-threshold: 3
      send-on-resolved: true

endpoints:
  - name: Nextcloud
    # Edit url
    url: https://nextcloud.local.local/login
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

ui:
  title: My Monitor
