version: '3.3'

services:
  slapd:
    user: root
    image: bitnami/openldap
    restart: always
    environment:
      LDAP_ADMIN_PASSWORD: Operator2022!
      LDAP_ROOT: dc=homelab,dc=local
      LDAP_CONFIG_ADMIN_ENABLED: 1
      LDAP_CONFIG_ADMIN_USERNAME: configadmin
    ports:
      - 389:1389
    volumes:
      - ./loginUser.ldif:/custom/loginUser.ldif
      - ./openldap-container:/bitnami/openldap/:rw
    deploy:
      resources:
        limits:
          memory: 10M
  radius:
    build: 
      context: ./freeradius-ldap
    restart: always
    ports: 
      - 1812:1812/udp
    volumes:
      - ./freeradius-ldap/ldap.conf:/etc/raddb/mods-available/ldap
    deploy:
      resources:
        limits:
          memory: 15M
