version: '3.9'

services:
  # AdGuard DNS blackhole
  adguard:
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
    restart: unless-stopped
    volumes:
      - ./conf:/opt/adguardhome/conf/
