server:
  address: tcp://0.0.0.0:9091/
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

storage:
  local:
    path: /config/authelia.db

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'

log:
  level: info
  format: text
  file_path: '/config/logs/authelia.%d.log'
  keep_stdout: true

authentication_backend:
  ldap:
    address: ldap://lldap:3890
    implementation: lldap
    base_dn: ${LDAP_BASE_DN}
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    user: uid=authelia_bind_user,ou=people,${LDAP_BASE_DN}
    attributes:
      picture: jpegPhoto

totp:
  issuer: Authelia # Change the name to something you want

webauthn:
  display_name: Authelia # Change the name to something you want
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: 'two_factor'
  rules:
    # Protect the dashboard
  - domain: 'dash.${DOMAIN}'
    policy: 'one_factor'
    # Protect gatus
  - domain: 'gatus.${DOMAIN}'
    policy: 'bypass'
    resources:
    - '^/api/v1/endpoints/[a-z\-_]+/uptimes/24h/badge\.svg$'

session:
  cookies:
    - domain: ${DOMAIN}
      authelia_url: https://auth.${DOMAIN}
      inactivity: 10m
      expiration: 2h
      remember_me: 1d

identity_providers:
  oidc:
    jwks:
      - key_id: 'default'
        key: {{ secret "/secrets/private.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: ij3Nm6CB7t2dUFVyyxZCFyhucovj6S
        client_secret: 1yty2iGmCy14ip9uAE7bXisnv0sHRBx6LRuJDgYEVJo8dWXdpHqZdkUecohQHMX4
        redirect_uris:
          - 'https://example.com'
