version: "3.9"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped