version: '3.8'

services:
  # Uptime kuma uptime monitor
  uptime-kuma:
    image: louislam/uptime-kuma
    ports:
      - 3001:3001/tcp
    volumes:
      - uptime-kuma:/app/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Chyrp lite, a simple blogging platform
  # First run 'docker build -t chyrp .' in the 'chyrp-lite' folder to build the image
  # Follow https://chyrplite.net/wiki/Quick-Start-Guide.html#install-chyrp-lite for installation instructions
  chyrp:
    image: chyrp
    ports: 
      - 8080:8080
    volumes:
      - chyrp:/var/www
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 60M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # SQL server to save data for diffrent containers
  mysql:
    image: mariadb
    volumes:
      - mysql:/bitnami/mysql/data
    secrets:
      - mysql_root_pass
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pass
    configs:
      - source: mysql_init_script
        target: /docker-entrypoint-initdb.d/init.sql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

configs:
  raneto_js_conf:
    file: ./config.default.js
  mysql_init_script:
    file: ./init.sql

secrets:
  mysql_root_pass:
    file: ./mysql-root-pass.txt

volumes:
  uptime-kuma:
  pihole:
  dnsmasq:
  chyrp:
  mysql:
