version: '3.8'

services:
  # Chyrp lite, a simple blogging platform
  # First run 'docker build -t chyrp .' in the 'chyrp-lite' folder to build the image
  # Follow https://chyrplite.net/wiki/Quick-Start-Guide.html#install-chyrp-lite for installation instructions
  chyrp:
    image: chyrp
    ports: 
      - 8080:8080
    volumes:
      - chyrp:/var/www
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 60M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Statping
  statping:
    container_name: statping
    image: adamboutcher/statping-ng
    depends_on:
      - mysql
    ports:
      - 9090:8080
    volumes:
      - statping_data:/app
    links:
      - mysql
    environment:
      DB_CONN: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: statping
      DB_USER: statping
      DB_PASS: password
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # SQL server to save data for diffrent containers
  mysql:
    image: mariadb
    volumes:
      - mysql:/bitnami/mysql/data
    secrets:
      - mysql_root_pass
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pass
    configs:
      - source: mysql_init_script
        target: /docker-entrypoint-initdb.d/init.sql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

configs:
  mysql_init_script:
    file: ./init.sql

secrets:
  mysql_root_pass:
    file: ./mysql-root-pass.txt

volumes:
  chyrp:
  mysql:
  statping_data:
