version: '3.8'

services:
  # LDAP server
  slapd:
    user: root
    image: bitnami/openldap
    secrets:
      - ldap_admin_pass
      - ldap_configadmin_pass
    environment:
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/ldap_admin_pass
      LDAP_ROOT: dc=homelab,dc=local
      LDAP_CONFIG_ADMIN_ENABLED: 1
      LDAP_CONFIG_ADMIN_USERNAME: configadmin
      LDAP_CONFIG_ADMIN_PASSWORD_FILE: /run/secrets/ldap_configadmin_pass
    ports:
      - 389:1389
    volumes:
      - openldap:/bitnami/openldap/:rw
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 10M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Freeradius server
  # First run 'docker build -t freeradius-ldap-auth' in the 'freeradius-with-ldap-auth' folder to build the image
  # Edit 'ldap.conf' to comply with your LDAP server settings
  radius:
    image: freeradius-ldap-auth
    configs:
      - source: radius_client_list
        target: /radius-clients.json
      - source: radius_ldap_config
        target: /etc/raddb/mods-available/ldap
    secrets:
      - ldap_admin_pass
    ports: 
      - 1812:1812/udp
    depends_on:
      - slapd
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 15M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Pi-hole DNS blackhole
  pihole:
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    secrets:
      - pihole_web_pass
    environment:
      TZ: Europe/Amsterdam
      WEBPASSWORD_FILE: /run/secrets/pihole_web_pass
      DNSMASQ_LISTENING: all
    volumes:
      - phole:/etc-pihole
      - dnsmasq:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 30M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Uptime kuma uptime monitor
  uptime-kuma:
    image: louislam/uptime-kuma
    ports:
      - 3001:3001/tcp
    volumes:
      - uptime-kuma:/app/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 10M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Chyrp lite, a simple blogging platform
  # First run 'docker build -t chyrp .' in the 'chyrp-lite' folder to build the image
  # Follow https://chyrplite.net/wiki/Quick-Start-Guide.html#install-chyrp-lite for installation instructions
  chyrp:
    image: chyrp
    ports: 
      - 8080:8080
    volumes:
      - chyrp:/var/www
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 60M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  raneto:
    image: lscr.io/linuxserver/raneto:latest
    ports:
      - 3000:3000
    volumes:
      - raneto:/config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s
      


configs:
  radius_client_list:
    file: ./radius-clients.json

secrets:
  ldap_admin_pass:
    file: ./ldap-admin-pass.txt
  ldap_configadmin_pass:
    file: ./ldap-configadmin-pass.txt
  radius_ldap_config:
    file: ./ldap.conf
  pihole_web_pass:
    file: ./pihole-web-pass.txt

volumes:
  uptime-kuma:
  pihole:
  dnsmasq:
  openldap:
  chyrp:
  raneto:
