version: '3.8'

services:
  # LDAP server
  slapd:
    user: root
    image: bitnami/openldap
    secrets:
      - ldap_admin_pass
      - ldap_configadmin_pass
    environment:
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/ldap_admin_pass
      LDAP_ROOT: dc=homelab,dc=local
      LDAP_CONFIG_ADMIN_ENABLED: 1
      LDAP_CONFIG_ADMIN_USERNAME: configadmin
      LDAP_CONFIG_ADMIN_PASSWORD_FILE: /run/secrets/ldap_configadmin_pass
    ports:
      - 389:1389
    volumes:
      - openldap:/bitnami/openldap/:rw
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 10M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Freeradius server
  # First run 'docker build -t freeradius-ldap-auth' in the 'freeradius-with-ldap-auth' folder to build the image
  radius:
    image: freeradius-ldap-auth
    configs:
      - source: radius_client_list
        target: /radius-clients.json
    secrets:
      - ldap_admin_pass
    environment:
      LDAP_HOST: slapd
      LDAP_PORT: 1389
      LDAP_USER: cn=admin,dc=homelab,dc=local
      LDAP_PASS_FILE: /run/secrets/ldap_admin_pass
      LDAP_BASEDN: dc=homelab,dc=local
    ports: 
      - 1812:1812/udp
    depends_on:
      - slapd
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 15M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Pi-hole DNS blackhole
  pihole:
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    secrets:
      - pihole_web_pass
    environment:
      TZ: Europe/Amsterdam
      WEBPASSWORD_FILE: /run/secrets/pihole_web_pass
      DNSMASQ_LISTENING: all
    volumes:
      - phole:/etc-pihole
      - dnsmasq:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 30M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

  # Uptime kuma uptime monitor
  uptime-kuma:
    image: louislam/uptime-kuma
    ports:
      - 3001:3001/tcp
    volumes:
      - uptime-kuma:/app/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 10M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s

configs:
  radius_client_list:
    file: ./radius-clients.json

secrets:
  ldap_admin_pass:
    file: ./ldap-admin-pass.txt
  ldap_configadmin_pass:
    file: ./ldap-configadmin-pass.txt
  pihole_web_pass:
    file: ./pihole-web-pass.txt

volumes:
  uptime-kuma:
  pihole:
  dnsmasq:
  openldap:
