version: '3.9'

services:
  homeassistent:
    image: linuxserver/homeassistant
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - homeassistent:/config
