version: '3.8'

services:
  raneto:
    image: lscr.io/linuxserver/raneto:latest
    ports:
      - 300:3000
    volumes:
      - ./config:/config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s