# NOT SUPPOSED TO RUN IN SWARM MODE

version: "3.9"

services:
  # Frp to open up the connection to the internet
  frp:
    image: ghcr.io/nekoluka/frp-docker:main
    restart: unless-stopped
    volumes:
      - ./frp.ini:/frp.ini
    environment:
      - FRP_CONFIG_FILE=/frp.ini
      - FRP_VERSION=0.51.3

  # Nextcloud image with some default config
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
      - ./postgres-password.txt:/run/secrets/postgres-password.txt
      - ./nextcloud-password.txt:/run/secrets/nextcloud-password.txt
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password.txt
      POSTGRES_HOST: postgresql:5432
      NEXTCLOUD_TRUSTED_DOMAINS: # Fill nextcloud domain here
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud-password.txt
      TRUSTED_PROXIES: frp
      OVERWRITEHOST: # Fill nextcloud domain here
      OVERWRITEPROTOCOL: https
    ports:
      - "8080:80"

  # Postgres to save all the settings
  postgresql:
    image: postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-password.txt:/run/secrets/postgres-password.txt
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password.txt
      POSTGRES_DB: nextcloud

volumes:
  nextcloud:
  nextcloud_data:
  db:
