services:
  homeassistant:
    image: linuxserver/homeassistant
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - homeassistant:/config

  nodered:
    image: nodered/node-red:latest
    restart: unless-stopped
    volumes:
      - nodered:/data
    ports:
      - 1880:1880

volumes:
  homeassistant:
  nodered:
