version: "3.9"

services:
  organizr:
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Amsterdam