volumes:
  caddy_data:
  caddy_config:
  lldap_data:
  radicale_data:
  sakuradav_data:
  duplicati_data:

services:
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy.log:/etc/caddy/caddy.log
      - ./caddy/docs:/docs

  authelia:
    image: authelia/authelia:4.39.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:9091:9091
    environment:
      PUID: 1001
      PGID: 1001
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: '/secrets/LDAP_PASSWORD'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/secrets/HMAC_SECRET'
      # Custom env vars
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets

  lldap:
    image: lldap/lldap:2024-10-10-alpine
    restart: unless-stopped
    environment:
      UID: 1001
      GID: 1001
      TZ: Europe/Amsterdam
      LLDAP_JWT_SECRET_FILE: /secrets/JWT_SECRET
      LLDAP_LDAP_USER_PASS_FILE: /secrets/ADMIN_PASS
      LLDAP_KEY_SEED: Kn3NErqOdOvaKHgBrtp8
      LLDAP_LDAP_BASE_DN: ${LDAP_BASE_DN}
    ports:
      - 10.10.200.2:3890:3890
    volumes:
      - lldap_data:/data
      - ./lldap_config:/secrets

  gatus:
    image: twinproduction/gatus:v5.15.0
    restart: unless-stopped
    volumes:
      - ./gatus/config:/config

  radicale:
    image: nekoluka/radicale:3.4.1
    environment:
      BASE_DN: ${LDAP_BASE_DN}
    volumes:
      - radicale_data:/var/lib/radicale
      - ./radicale.config.ini:/var/radicale/config.ini
      - ./radicale-secret.txt:/radicale-secret.txt
    restart: unless-stopped

  sakuradav:
    image: nekoluka/sakuradav:0.1.1
    restart: unless-stopped
    environment:
      SAKURA_CONFIG: /config.yaml
    volumes:
      - ./sakuradav-config.yaml:/config.yaml
      - sakuradav_data:/webdav

  sakuradash:
    image: nekoluka/sakuradash
    restart: unless-stopped
    volumes:
      - ./sakuradash-config.yaml:/config.yaml

  duplicati:
    image: duplicati/duplicati:2.1.0.119
    restart: unless-stopped
    volumes:
      - lldap_data:/lldap
      - sakuradav_data:/sakuradav
      - radicale_data:/radicale
      - duplicati_data:/data
