version: '3.9'

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    ports:
      - 127.0.0.1:9091:9091
    environment:
      AUTHELIA_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - './authelia/config:/config'
      - './authelia/secrets:/secrets'

  gatus:
    image: twinproduction/gatus
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./gatus/config:/config
    restart: unless-stopped
