volumes:
  caddy_data:
  caddy_config:
  ntfy_config:
  ntfy_cache:
  lldap_data:
  radicale_data:
  wikidocs_datasets:
  mosquitto_data:
  mosquitto_log:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  wgnet: # Subnet 172.20.0.0/24
    external: true

services:
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
    network_mode: service:wireguard
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  authelia:
    image: authelia/authelia:4.38.16
    restart: unless-stopped
    ports:
      - 127.0.0.1:9091:9091
    environment:
      PUID: 1001
      PGID: 1001
      X_AUTHELIA_CONFIG_FILTERS: expand-env,template
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: '/secrets/LDAP_PASSWORD'
      # Custom env vars
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets

  lldap:
    image: lldap/lldap:2024-10-10-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:17170:17170
      - 6360:6360
    environment:
      UID: 1001
      GID: 1001
      TZ: Europe/Amsterdam
      LLDAP_JWT_SECRET_FILE: /secrets/JWT_SECRET
      LLDAP_LDAP_USER_PASS_FILE: /secrets/ADMIN_PASS
      LLDAP_KEY_SEED: Kn3NErqOdOvaKHgBrtp8
      LLDAP_LDAP_BASE_DN: ${LDAP_BASE_DN}
      LLDAP_LDAPS_OPTIONS__ENABLED: true
      LLDAP_LDAPS_OPTIONS__CERT_FILE: /secrets/certificate.crt
      LLDAP_LDAPS_OPTIONS__KEY_FILE: /secrets/private.key
    volumes:
      - lldap_data:/data
      - ./lldap_config:/secrets

  gatus:
    image: twinproduction/gatus:v5.15.0
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:8080:8080
    network_mode: service:wireguard
    volumes:
      - ./gatus/config:/config

  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    command:
      - serve
    ports:
      - 22500:25
      # - 127.0.0.1:8888:80
    environment:
      TZ: Europe/Amsterdam    # optional: set desired timezone
      NTFY_BASE_URL: https://ntfy.${DOMAIN}
      NTFY_SMTP_SERVER_DOMAIN: ntfy.${DOMAIN}
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_config:/etc/ntfy
      - ./ntfy-server.yml:/etc/ntfy/server.yml

  radicale:
    image: nekoluka/radicale:3.4.1
    environment:
      BASE_DN: ${LDAP_BASE_DN}
    volumes:
      - radicale_data:/var/lib/radicale
      - ./radicale.config.ini:/var/radicale/config.ini
      - ./radicale-secret.txt:/radicale-secret.txt
    restart: unless-stopped

  wikidocs:
    image: zavy86/wikidocs
    restart: unless-stopped
    volumes:
      - wikidocs_datasets:/datasets

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883

  sakuradash:
    image: nekoluka/sakuradash
    restart: unless-stopped
    volumes:
      - ./sakuradash-config.yaml:/config.yaml

  wireguard:
    image: linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wg.conf:/config/wg_confs/wg.conf
      - ./wg-backup.conf:/config/wg_confs/wg-backup.conf
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
        ipv4_address: 172.18.0.50
      wgnet:
        ipv4_address: 172.20.0.50
