serverBindString: ":9090"
fileRootDir: /webdav
ldapConfig:
  connectionString: ldap://lldap:3890
  DNTemplate: uid=%s,ou=people,dc=nekoluka,dc=nl
joplinConfig:
  isEnabled: true
regularWebDav:
  isEnabled: false
