volumes:
  jellyfin_cache:
  jellyfin_config:
  jellyseerr_config:

services:
  jellyfin:
    image: linuxserver/jellyfin
    ports:
      - 8096:8096
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: /mnt/jellyfin
        target: /media
    restart: 'unless-stopped'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped
