volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Amsterdam
      CRON_MIN: '3,33'