version: '3.9'

volumes:
  tamari-data:
    driver: local

services:
  tamari:
    image: alexbates/tamari:0.5
    restart: unless-stopped
    volumes:
      - tamari-data:/app/appdata
    ports:
      - 4888:4888
