version: '3.9'

services:
  frpc:
    image: snowdreamtech/frpc:0.57.0
    restart: unless-stopped
    environment:
      - FRP_SERVER_ADDR=x.x.x.x
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
