serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7070

transport.poolCount = 5
transport.useEncryption = true
transport.useCompression = true
transport.proxyProtocolVersion = "v2"

log.to = "/frpc.log"
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "supersecrettoken"

[Immich]
name = "web"
type = "http"
localIP = "immich.lan"
localPort = 3001
remote_port = 8080
customDomains = "immich.remote.remote"

[Vaultwarden]
name = "web"
type = "http"
localIP = "vaultwarden.lan"
localPort = 9000
remote_port = 8080
customDomains = "vaultwarden.remote.remote"

[Owncloud]
name = "web"
type = "http"
localIP = "owncloud.lan"
localPort = 8080
remote_port = 8080
customDomains = "owncloud.remote.remote"
