serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7070

transport.poolCount = 5
transport.useEncryption = true
transport.useCompression = true
transport.proxyProtocolVersion = "v2"

log.to = "/frpc.log"
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "supersecrettoken"

[MinIO]
name = "web"
type = "http"
localIP = "s3.local.local"
localPort = 9000
remote_port = 8080
customDomains = "s3.remote.remote"

[Nextcloud]
name = "web"
type = "http"
localIP = "nextcloud.local.local"
localPort = 80
remote_port = 8080
customDomains = "nextcloud.remote.remote"

[Immich]
name = "web"
type = "http"
localIP = "immich.local.local"
localPort = 3001
remote_port = 8080
customDomains = "immich.remote.remote"

[Vaultwarden]
name = "web"
type = "http"
localIP = "vaultwarden.local.local"
localPort = 9000
remote_port = 8080
customDomains = "vaultwarden.remote.remote"
