version: '3.8'

services:
  # Wireguard 
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      TZ: Europe/Amsterdam
      SERVERURL: 192.168.2.197
      PEERS: myPC
      ALLOWEDIPS: 10.13.13.0/24,10.10.255.0/24
      LOG_CONFS: false
    volumes:
      - /usr/src:/lib/modules
      - ./wireguard-config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s
